### ISSUE TITLE
Alphabetical order in command list.

### ISSUE THREAD

**Issue by Cardoso222** [Idnan/bash-guide#11]
Maybe the search for commands will be more easy if we change to alphabetical order.

**Comment by TrostAft** [comment]
I would argue that a order of significance would make more sense, like **ssh** before **scp,** but there is no real way to score that. 

Maybe try and do by significance for the master guide and include an appendix of everything in alphabetical order?

**Comment by Cardoso222** [comment]
Its hard to define the level of significance for some commands, sometimes what is significant for me isn't for you and vice-versa. But this is a good suggestion!

**Comment by Idnan** [comment]
Alphabetical order makes more sense.
