### ISSUE TITLE
A bash guide shouldn't use zsh for examples

### ISSUE THREAD

**Issue by josephgrossberg** [Idnan/bash-guide#26]
Instead of using this to demonstrate **export**:

```sh
$ export
SHELL=/bin/zsh
AWS_HOME=/Users/adnanadnan/.aws
LANG=en_US.UTF-8
LC_CTYPE=en_US.UTF-8
LESS=-R

$ echo $SHELL
/usr/bin/zsh
```

let's omit `zsh`, which is an **alternative** to `bash`. That's confusing, and at cross-purposes with this tutorial.

I suggest updating that part of the README to this:

```sh
$ export
AWS_HOME=/Users/adnanadnan/.aws
LANG=en_US.UTF-8
LC_CTYPE=en_US.UTF-8
LESS=-R

$ echo $AWS_HOME
/Users/adnanadnan/.aws
```

**Comment by Idnan** [comment]
Thanks @josephgrossberg

**Comment by josephgrossberg** [comment]
TY! Good guide; this is nice. 👍
