### ISSUE TITLE
The if statement is not right in the conditional part

### ISSUE THREAD

**Issue by Celthi** [Idnan/bash-guide#50]
The `if` part that `if [expression]; then` should be `if [ expression ]; then`. There must be space after [ and before ]see the [link](http://stackoverflow.com/questions/9581064/why-should-there-be-a-space-after-and-before-in-bash)

And it will be better if there is an example given.

**Comment by lhoursquentin** [comment]
The brackets should actually be removed entirely as the `if` syntax is `if command; then` where **command** can be anything like `ls` or `tree` for instance, if executes the command and branches into the `if` body if the latter returns 0 or in the `else/elif` body for any other return value.
This should not be restricted to the use of `[` that is a builtin (and an equivalent to `test`) often used in condition but all in all remains a simple command.

**Comment by Celthi** [comment]
Yeah, you are right. Maybe you can fix the error.
